services:
  app:
    build: 
      context: $PWD/app
      dockerfile: $PWD/app/Dockerfile.local
    volumes:
      - $PWD/app:/app/
    command: npm run dev

  caddy:
    volumes:
      - $PWD/caddy/Caddyfile.local:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
