services:
  app:
    build: ./app/Dockerfile

  caddy:
    image: caddy:2.8-alpine
    restart: unless-stopped
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile
