services:
  app:
    build: ./app

  caddy:
    image: caddy:2.8-alpine
    restart: unless-stopped
    extends:
      file: $PWD/caddy/${ENV_NAME:?error}/caddy.yaml
      service: caddyapp
    volumes:
      - $PWD/caddy/${ENV_NAME:?error}/Caddyfile:/etc/caddy/Caddyfile
    env_file:
      - $PWD/.env