services:
  app:
    build: ./app
    # env_file:
    #   - ./env/app.env
    # depends_on:
    #   db:
    #     condition: service_healthy

  caddy:
    image: caddy:2.8-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile

  # secrets:
  #   github-auth:
  #    file: $PWD/secrets/github-auth.txt

  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: example
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready"]
  #     interval: 1s
  #     timeout: 5s
  #     retries: 10
