import type { Metadata } from "next";
import { M_PLUS_1p } from "next/font/google";

import "@/styles/globals.css";
import "@/styles/typography.css";

const font = M_PLUS_1p({ subsets: ["latin"], weight: ["100","300","400","700"] });

export const metadata: Metadata = {
  title: "Daglesium",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
