name: Tranquility
on: [push]
jobs:
  app:
    name: Frontend
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Build
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install
        run: npm ci
      - name: Linter
        run: npm run lint
      - name: Unit tests
        run: npm run test
